#!/bin/bash
set -e

ERROR="\e[31m[ERROR]: \e[0m"
INFO="\e[32m[INFO]: \e[0m"
WARNING="\e[33m[WARNING]: \e[0m"

dir=$(pwd)

echo -e "${INFO}Install tools"
source $dir/scripts/install-tools


echo -e "${INFO}Installing and setting up tmux, zsh, and neovim"

# --->tmux<---

echo -e "${INFO}tmux: setup"

# get tpm (to download tmux plugins)
echo -e "${INFO}tmux: cloning tpm (if not already installed)"
[ ! -d $HOME/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

# symlink tmux config
echo -e "${INFO}tmux: symlink config file"
ln -s $dir/tmux/.tmux.conf $HOME/.tmux.conf

# --->zsh<---

echo -e "${INFO}zsh: setup"

echo -e "${INFO}zsh: cloning ohmyzsh"
[ ! -d $HOME/.oh-my-zsh ] && git clone https://github.com/ohmyzsh/ohmyzsh.git $HOME/.oh-my-zsh

echo -e "${INFO}zsh: install zsh plugins"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo -e "${INFO}zsh: symlink zsh config files"
ln -s $dir/zsh/.zshrc $HOME/.zshrc
ln -s $dir/zsh/alias.zsh ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/alias.zsh
ln -s $dir/zsh/frahz.zsh-theme ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/frahz.zsh-theme


# --->neovim<---

echo -e "${INFO}neovim: setup"

echo -e "${INFO}neovim: install/build neovim"

pushd $HOME/temp
wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar -xvzf nvim-linux64.tar.gz
sudo ln -s $HOME/temp/nvim-linux64/bin/nvim /usr/bin/nvim
popd

echo -e "${INFO}neovim: symlink config files"
ln -s $dir/.config/nvim $HOME/.config/nvim

